### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by adrianschneider94** [bpmn-io/bpmn-to-image#12]
Hi,

I want(ed) to use your package to render BPMN files (as svg) in gitea -- but I don't like the dependency on Puppet/Chromium. My docker image would be enormous for such a little task. I thought that bpmn-js itself can export SVG data -- why this very heavy dependency?

Best wishes
Adrian Schneider

**Comment by nikku** [comment]
Two points here:

* we use the DOM to render the diagrams
* we have to layout the text to look nice, that requires kerning information, only available on systems with a X11 or other graphical environment present
