### ISSUE TITLE
Feat: Add support for DMN files

### ISSUE THREAD

**Issue by sualko** [bpmn-io/bpmn-to-image#19]
Hi everyone,

I need to convert DMN files to images so I forked this repo and added support for it, see https://github.com/sualko/bpm-to-image

It would be great if we could merge this here, but since it's quite different from the initial purpose I first wanted to ask if you are interested. Should I prepare a pull request?

**Comment by nikku** [comment]
What about creating a library called `dmn-to-image` that does the above? I believe it is fine to have both coexist. 

We're happy to link "dmn-to-image" if you create it. 

Do you see any benefit I'm missing of having both in a single tool?

**Comment by sualko** [comment]
Thanks for the fast reply.

> Do you see any benefit I'm missing of having both in a single tool?

The benefit from having one unified tool is the reduced maintenance effort. As you can see, the difference between DMN and BPMN is quite small. If you have two tools and you find a bug, it is likely that you have to fix it twice and also release two new versions.

**Comment by nikku** [comment]
I could imagine having a tool `@bpmn-io/to-image` in the future that bundles _to image_ functionality for all our toolkits under the hood. For the moment we do not have the intend to include DMN to image into this tool.

It is great you shared your tool so others may benefit from it :+1:.
