### ISSUE TITLE
Added parameter/flag for expand/collapse subprocesses

### ISSUE THREAD

**Issue by codebude** [bpmn-io/bpmn-to-image#21]
__Is your feature request related to a problem? Please describe__

The bpmn-to-image is a great tool, but unfortunately as soon as subprocesses (e.g. catch/exception handler process) come into play, it's not that useful, because the images rendered don't show the contents of subprocesses. (Because all subprocesses are renderer in a collapsed state.)

__Describe the solution you'd like__

I would love to see an additional cli paramter that allows to auto-expand all subprocesses when rendering the diagram.

__Describe alternatives you've considered__

Can't think of any alternatives. (At least no practicable.)

**Comment by nikku** [comment]
Could you provide an example that visualizes what you'd like to achieve? If you decided to have sub-processes collapsed, why should they be expanded in the generated image? And how do you imagine these expand without breaking the diagram layout?

The goal of this library is to generate an image of your BPMN file _as is_ and not to generate an image showing all details. I could imagine the later one is hard to accomplish, without a trade off.

**Comment by codebude** [comment]
Hi @nikku ,

thanks for the fast response. Let me give some background/context:

I'm working with a SAP integration tool called "SAP CPI". Integration scenarios are defined in a graphical way:
![vm-at-sap](https://user-images.githubusercontent.com/2236234/115515325-4d876100-a285-11eb-81e6-e82f914efc5c.png)

These flows are defined in BPMN notation in background. The BPMN file for the flow above can be found here:
https://gist.github.com/codebude/35e019256235adea40d861af11c42da8

When creating a graphic with BPMN.io it looks like:
![dia](https://user-images.githubusercontent.com/2236234/115515759-ba9af680-a285-11eb-9b56-50cd15806136.png)

What I would expect to see is:
![dia-expanded](https://user-images.githubusercontent.com/2236234/115516013-fdf56500-a285-11eb-8440-fe7e6331bfca.png)

**Comment by nikku** [comment]
This looks like a bug, not a feature request to me.

Unfortunately the GIST is not accessible to me. Could you share it as an attachment to your issue with the `bpmn.txt` extension?

**Comment by codebude** [comment]
> Unfortunately the GIST is not accessible to me. Could you share it as an attachment to your issue with the `bpmn.txt` extension?

Nothing easier than that. :-)
[bpmn.txt](https://github.com/bpmn-io/bpmn-to-image/files/6349294/bpmn.txt)

**Comment by barmac** [comment]
This looks like a bug in your modeling tool. The SubProcess' DI looks like this:

```xml
            <bpmndi:BPMNShape bpmnElement="SubProcess_9856" id="BPMNShape_SubProcess_9856">
                <dc:Bounds height="140.0" width="414.0" x="1355.0" y="257.0"/>
            </bpmndi:BPMNShape>
```

The `isExpanded` attribute is missing. According to [the BPMN 2.0 spec](https://www.omg.org/spec/BPMN/2.0/PDF#page=416), if this attribute is missing or set to false, the SubProcess should be rendered in its collapsed form.

**Comment by codebude** [comment]
Hi @barmac ,

adding the attribute works totally fine. I will open a ticket at SAP and ask them if it's possible to add the attribute. Thanks for the quick support!
