### ISSUE TITLE
Unable to run under root

### ISSUE THREAD

**Issue by Vanderhoof** [bpmn-io/bpmn-to-image#22]
First of all thank you for a nice tool!

Since [this](https://github.com/bpmn-io/bpmn-to-image/commit/fa51f4f29ad441694c2c06339e01ede7c298d90e) commit and release 0.6.0 I can't run `bpmn-to-image` under sudo. 

We are running `bpmn-to-image` inside a Docker container so running under root is a must for us. WIth `--no-sandbox` option for chromium removed in the aforementioned commit we now get an error:

```
Error: Failed to launch the browser process!
[0802/120743.010301:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

Maybe there is some other option to make **bpmn-to-image 0.6.0** work under root? If not, I am kindly requesting it, so we won't have to stick to the still working **0.5.1**.

**Comment by pinussilvestrus** [comment]
We removed the flag due to security concerns, cf. https://github.com/bpmn-io/bpmn-to-image/issues/14. What I can think of is to provide arguments via options. So something like

```js
// from somewhere outside
const options = { 
   launchArgs: [
      '--no-sandbox'
    ]
};

// inside the tool
const { launchArgs: args } = options;

browser = await puppeteer.launch({
      args
});
```

and then to use at own risk.

**Comment by pinussilvestrus** [comment]
Would that help or do you already find another workaround to make it run on root?

**Comment by nikku** [comment]
Docker [can be run in non-root mode](https://docs.docker.com/engine/security/rootless/). Would that work as a workaround for you?

**Comment by nikku** [comment]
Closing this one as non-root access in a docker container is possible.

We are open to a PR that restores the `--no-sandbox` flag via an environment variable:

`DANGEROUSLY_DISABLE_SANDBOX=1 bpmn-to-image`.
