### ISSUE TITLE
Unable to install on M1 Mac

### ISSUE THREAD

**Issue by mntlty** [bpmn-io/bpmn-to-image#23]
__Describe the Bug__

I am unable to install on an M1 mac due to an outdated version of pupetteer. This issue was fixed in v10+ https://github.com/puppeteer/puppeteer/issues/6622

![Screen Shot 2021-11-02 at 8 34 19 AM](https://user-images.githubusercontent.com/1149246/139878862-b5ed37a2-90be-4fd7-a648-af28163a443c.png)

__Steps to Reproduce__

1. use an M1 mac
2. run `npm install -g bpmn-to-image`

__Expected Behavior__

installation is successful

__Environment__

- OS: OS X 11.6 (Big Sur)
- Library version: 0.6.1

**Comment by nikku** [comment]
Fixed with `v0.6.1`.
