### ISSUE TITLE
TypeError when running the example code

### ISSUE THREAD

**Issue by kirstenhh** [bpmn-io/bpmn-to-image#28]
__Describe the Bug__

Embedded code fails in development mode with "TypeError : The "original" argument must be of type function"
This appears to be a known problem coming from Puppeteer; I'm simply hoping there's a workaround that I could take advantage of. 

__Steps to Reproduce__

1. Include the embedding code given as an example in the README in any package file. 
2. run npm start
3. check the page in browser: the above error appears in console. 

__Expected Behavior__

Printing to images, or absence of the error. 

__Environment__
- Firefox v102.0.1 and Chrome v103.0.5060.114, Node v16.15.0, npm v8.5.5, puppeteer v15.4.0
- OS: Windows 10
- Library version: v0.6.1

**Comment by pinussilvestrus** [comment]
Are you able to share your setup by any chance? E.g. via [CodeSandbox](https://codesandbox.io/)?

**Comment by kirstenhh** [comment]
I can't share the current setup unfortunately - it's a private repo and I'm not the owner. I'm trying to replicate the issue now using one of the bpmn-js examples, but I get a different error instead so I'm still working on that.

**Comment by pinussilvestrus** [comment]
Any updates on this one?

**Comment by kirstenhh** [comment]
I apologize - I forgot I'd left this open. I realized shortly after writing this that A) I was trying to use it with BPMN 7, and that B) I needed to upgrade the whole thing to BPMN 9. Therefore I think it was a version issue, and I'm using some different packages instead. Thank you!

**Comment by pinussilvestrus** [comment]
Thanks for the update 👍
