### ISSUE TITLE
Unable to run as a part of react.js code

### ISSUE THREAD

**Issue by sochoterez** [bpmn-io/bpmn-to-image#29]
Hi,
I try to embed **bpmn-to-image** package to **react.js** project. After installing package I get errors connected to **polyfills** for **node.js** and errors connected to **fs** and **child_process** package. Is there somebody who has the same problem. Is there a way how to solve it  ?

**Steps how to reproduce error**
1. Create  react project named test by command : **npx create-react-app test** 
2. Install bpm-to-image by command: **npm install bpmn-to-image** 
3. Add button to react 
4. Add click handler on button with code from bpm-to-image readme
5. Strat project by command: **npm start**

*Expected Behaviour***

Start app without errors

Enviroment

- Host:  bpm-to-image 0.6.1, Google Chrome, webpack 5.74.0
- OS: Windows 10
- Library version: webpack 5.74.0

**Comment by nikku** [comment]
That is due to the fact that this utility is meant for commandline / NodeJS usage.

It is not meant as a browser utility.
