### ISSUE TITLE
 Error: Evaluation failed: TypeError: Cannot read property 'importXML' of undefined

### ISSUE THREAD

**Issue by myzhoulang** [bpmn-io/bpmn-to-image#3]
There was a mistake according to this column.

![image](https://user-images.githubusercontent.com/7009272/54417878-54565800-473e-11e9-8f4c-4e69742107e3.png)
![image](https://user-images.githubusercontent.com/7009272/54417936-6df79f80-473e-11e9-8e0c-1172ba52d2e2.png)

**Comment by nikku** [comment]
What is your environment? Which version of `bpmn-to-image` do you use?

**Comment by myzhoulang** [comment]
@nikku 
macOS Mojave

node v10.15.1

![image](https://user-images.githubusercontent.com/7009272/54509681-51997400-4985-11e9-870d-60740d09bea7.png)

**Comment by nikku** [comment]
Unfortunately I cannot reproduce the issue you're describing.

Please provide us with an example project that reproduces the error / we can `npm install`.

**Comment by nikku** [comment]
I was able to reproduce given another users input.

Fix released as `v0.3.1`.
