### ISSUE TITLE
Cannot read property 'importXML' of undefined

### ISSUE THREAD

**Issue by KaiqueBressi** [bpmn-io/bpmn-to-image#5]
I was trying to test the `bpmn-to-image` and i faced the following error: `Evaluation failed: TypeError: Cannot read property 'importXML' of undefined`

Commands i was using to test: 
```
yarn init -y
yarn install bpmn-to-image
yarn run bpmn-to-image diagram.bpmn:diagram.png
``` 

After facing the error i started to investigate it. The line 8 of the `skeleton.html` is trying to load the script on the dir: `node_modules/bpmn-js/dist/bpmn-viewer.production.min.js` but the `bpmn-js` is on the same directory structure as the `bpmn-to-image` causing the script to never get loaded.

Replacing the `node_modules/bpmn-js` by `../bpmn-js` correct this problem, but i dont know what would be better to a definitive solution.

**Comment by nikku** [comment]
Thanks for the report and the detailed reproduction. I'll have a look.
